#!/usr/bin/env python3
"""
Test API - MCP Server
Generated by MCP Server Foundry

This server implements the Model Context Protocol (MCP) for Test API.
"""

import asyncio
import json
import sys
from typing import Any, Dict, List, Optional
from dataclasses import dataclass


@dataclass
class Tool:
    """Represents an MCP tool."""
    name: str
    description: str
    input_schema: Dict[str, Any]


@dataclass
class MCPRequest:
    """Represents an incoming MCP request."""
    jsonrpc: str
    id: Optional[int]
    method: str
    params: Optional[Dict[str, Any]] = None


@dataclass
class MCPResponse:
    """Represents an MCP response."""
    jsonrpc: str
    id: Optional[int]
    result: Optional[Any] = None
    error: Optional[Dict[str, Any]] = None


class MCPServer:
    """
    MCP Server implementation for Test API.
    
    This server exposes API endpoints as MCP tools that can be called
    by MCP-compatible clients.
    """
    
    def __init__(self):
        self.tools: List[Tool] = []
        self._register_tools()
    
    def _register_tools(self):
        """Register all available tools."""
        self.tools.append(Tool(
            name="getUser",
            description="Get user by ID",
            input_schema={"properties": {"user_id": {"description": "ID of the user to retrieve", "type": "integer"}}, "required": ["user_id"], "type": "object"}
        ))
        self.tools.append(Tool(
            name="createUser",
            description="Create new user",
            input_schema={"properties": {"email": {"format": "email", "type": "string"}, "username": {"maxLength": 50, "minLength": 3, "type": "string"}}, "required": ["username", "email"], "type": "object"}
        ))
        self.tools.append(Tool(
            name="listTasks",
            description="List tasks",
            input_schema={"properties": {"limit": {"description": "Maximum number of tasks to return", "type": "integer"}, "status": {"description": "Filter tasks by status", "type": "string"}}, "required": [], "type": "object"}
        ))
        self.tools.append(Tool(
            name="createTask",
            description="Create new task",
            input_schema={"properties": {"description": {"maxLength": 2000, "type": "string"}, "due_date": {"format": "date", "type": "string"}, "priority": {"default": 3, "maximum": 5, "minimum": 1, "type": "integer"}, "status": {"default": "pending", "enum": ["pending", "in_progress", "completed", "cancelled"], "type": "string"}, "title": {"maxLength": 200, "minLength": 1, "type": "string"}}, "required": ["title"], "type": "object"}
        ))
    
    async def handle_request(self, request: MCPRequest) -> MCPResponse:
        """
        Handle an incoming MCP request.
        
        Args:
            request: The MCP request to handle
            
        Returns:
            MCP response with result or error
        """
        try:
            if request.method == "initialize":
                return self._handle_initialize(request)
            elif request.method == "tools/list":
                return self._handle_list_tools(request)
            elif request.method == "tools/call":
                return await self._handle_call_tool(request)
            else:
                return MCPResponse(
                    jsonrpc="2.0",
                    id=request.id,
                    error={
                        "code": -32601,
                        "message": f"Method not found: {request.method}"
                    }
                )
        except Exception as e:
            return MCPResponse(
                jsonrpc="2.0",
                id=request.id,
                error={
                    "code": -32603,
                    "message": f"Internal error: {str(e)}"
                }
            )
    
    def _handle_initialize(self, request: MCPRequest) -> MCPResponse:
        """Handle initialize request."""
        return MCPResponse(
            jsonrpc="2.0",
            id=request.id,
            result={
                "protocolVersion": "2024-11-05",
                "capabilities": {
                    "tools": {}
                },
                "serverInfo": {
                    "name": "test-api-mcp-server",
                    "version": "1.0.0"
                }
            }
        )
    
    def _handle_list_tools(self, request: MCPRequest) -> MCPResponse:
        """Handle tools/list request."""
        return MCPResponse(
            jsonrpc="2.0",
            id=request.id,
            result={
                "tools": [
                    {
                        "name": tool.name,
                        "description": tool.description,
                        "inputSchema": tool.input_schema
                    }
                    for tool in self.tools
                ]
            }
        )
    
    async def _handle_call_tool(self, request: MCPRequest) -> MCPResponse:
        """Handle tools/call request."""
        if not request.params or "name" not in request.params:
            return MCPResponse(
                jsonrpc="2.0",
                id=request.id,
                error={
                    "code": -32602,
                    "message": "Invalid params: 'name' is required"
                }
            )
        
        tool_name = request.params["name"]
        arguments = request.params.get("arguments", {})
        
        # Route to appropriate tool handler
        if tool_name == "getUser":
            return await self._call_getUser(request.id, arguments)
        if tool_name == "createUser":
            return await self._call_createUser(request.id, arguments)
        if tool_name == "listTasks":
            return await self._call_listTasks(request.id, arguments)
        if tool_name == "createTask":
            return await self._call_createTask(request.id, arguments)
        
        return MCPResponse(
            jsonrpc="2.0",
            id=request.id,
            error={
                "code": -32602,
                "message": f"Unknown tool: {tool_name}"
            }
        )
    
    async def _call_getUser(self, request_id: Optional[int], arguments: Dict[str, Any]) -> MCPResponse:
        """
        Handle getUser tool call.
        
        Get user by ID
        """
        # TODO: Implement actual API call
        # For now, return mock response
        return MCPResponse(
            jsonrpc="2.0",
            id=request_id,
            result={
                "content": [
                    {
                        "type": "text",
                        "text": f"Mock response for getUser with arguments: {json.dumps(arguments)}"
                    }
                ]
            }
        )
    
    async def _call_createUser(self, request_id: Optional[int], arguments: Dict[str, Any]) -> MCPResponse:
        """
        Handle createUser tool call.
        
        Create new user
        """
        # TODO: Implement actual API call
        # For now, return mock response
        return MCPResponse(
            jsonrpc="2.0",
            id=request_id,
            result={
                "content": [
                    {
                        "type": "text",
                        "text": f"Mock response for createUser with arguments: {json.dumps(arguments)}"
                    }
                ]
            }
        )
    
    async def _call_listTasks(self, request_id: Optional[int], arguments: Dict[str, Any]) -> MCPResponse:
        """
        Handle listTasks tool call.
        
        List tasks
        """
        # TODO: Implement actual API call
        # For now, return mock response
        return MCPResponse(
            jsonrpc="2.0",
            id=request_id,
            result={
                "content": [
                    {
                        "type": "text",
                        "text": f"Mock response for listTasks with arguments: {json.dumps(arguments)}"
                    }
                ]
            }
        )
    
    async def _call_createTask(self, request_id: Optional[int], arguments: Dict[str, Any]) -> MCPResponse:
        """
        Handle createTask tool call.
        
        Create new task
        """
        # TODO: Implement actual API call
        # For now, return mock response
        return MCPResponse(
            jsonrpc="2.0",
            id=request_id,
            result={
                "content": [
                    {
                        "type": "text",
                        "text": f"Mock response for createTask with arguments: {json.dumps(arguments)}"
                    }
                ]
            }
        )
    

async def main():
    """Main server loop."""
    server = MCPServer()
    
    print("Test API MCP Server started", file=sys.stderr)
    print(f"Registered {len(server.tools)} tools", file=sys.stderr)
    
    # Read requests from stdin, write responses to stdout
    while True:
        try:
            line = sys.stdin.readline()
            if not line:
                break
            
            request_data = json.loads(line)
            request = MCPRequest(
                jsonrpc=request_data.get("jsonrpc", "2.0"),
                id=request_data.get("id"),
                method=request_data["method"],
                params=request_data.get("params")
            )
            
            response = await server.handle_request(request)
            
            response_data = {
                "jsonrpc": response.jsonrpc,
                "id": response.id
            }
            
            if response.result is not None:
                response_data["result"] = response.result
            if response.error is not None:
                response_data["error"] = response.error
            
            print(json.dumps(response_data), flush=True)
            
        except json.JSONDecodeError as e:
            error_response = {
                "jsonrpc": "2.0",
                "id": None,
                "error": {
                    "code": -32700,
                    "message": f"Parse error: {str(e)}"
                }
            }
            print(json.dumps(error_response), flush=True)
        except KeyError as e:
            error_response = {
                "jsonrpc": "2.0",
                "id": None,
                "error": {
                    "code": -32600,
                    "message": f"Invalid request: missing {str(e)}"
                }
            }
            print(json.dumps(error_response), flush=True)
        except Exception as e:
            print(f"Unexpected error: {str(e)}", file=sys.stderr)
            break


if __name__ == "__main__":
    asyncio.run(main())